### PR TITLE
Unit test to deploy, execute, and undeploy CWL DAG

### PR DESCRIPTION
**Pull request by nikki-t**
## Purpose

- Create unit tests to test the deployment, execution, and un-deployment of this [CWL DAG](https://github.com/unity-sds/unity-sps/blob/develop/airflow/dags/cwl_dag.py).
- Execute with the default parameters: [CWL workflow](https://raw.githubusercontent.com/unity-sds/unity-sps-workflows/main/demos/echo_message.cwl) and argument of `{"message": "Hello Unity"}`.

## Proposed Changes

- [ADD] Unit tests: deploy, execute, status, and undeploy for CWL DAG.

## Issues

- [#131](https://github.com/unity-sds/unity-sps/issues/131) - Create test to deploy, execute and undeploy the CWL DAG

## Testing

- Local unit tests executed as expected:

```bash
collected 16 items                                                                   

unity-test/test_main.py::test_get_landing_page PASSED                          [  6%]
unity-test/test_main.py::test_get_health PASSED                                [ 12%]
unity-test/test_main.py::test_get_conformance_declaration PASSED               [ 18%]
unity-test/test_main.py::test_post_deploy_process PASSED                       [ 25%]
unity-test/test_main.py::test_delete_undeploy_process PASSED                   [ 31%]
unity-test/test_main.py::test_post_execute_process PASSED                      [ 37%]
unity-test/test_main.py::test_delete_dismiss_execution PASSED                  [ 43%]
unity-test/test_main.py::test_get_process_description PASSED                   [ 50%]
unity-test/test_main.py::test_get_process_list PASSED                          [ 56%]
unity-test/test_main.py::test_get_job_list PASSED                              [ 62%]
unity-test/test_main.py::test_get_status PASSED                                [ 68%]
unity-test/test_main.py::test_get_results PASSED                               [ 75%]
unity-test/test_main.py::test_post_deploy_process_cwl_dag PASSED               [ 81%]
unity-test/test_main.py::test_post_execute_process_cwl_dag PASSED              [ 87%]
unity-test/test_main.py::test_get_status_cwl_dag PASSED                        [ 93%]
unity-test/test_main.py::test_delete_undeploy_cwl_dag PASSED                   [100%]

================================== warnings summary ==================================
../../../environments/../lib/python3.12/site-packages/httpx/_models.py:1
  /../../../../../../lib/python3.12/site-packages/
    httpx/_models.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== 16 passed, 1 warning in 1.60s ============================
```

- Unit tests passed via GitHub Action. Results located [here](https://github.com/unity-sds/unity-sps-ogc-processes-api/actions/runs/9762634904/job/26946574913?pr=14).

### CODE REVIEW

**Review by drewm-swe — CHANGES_REQUESTED** [review]
Hi @nikki-t,

This is really great progress, diving into an existing codebase is never easy but I'm glad you were able to dig in so quickly.


I have one change request which is to use [pytest parameterization](https://docs.pytest.org/en/7.0.x/how-to/parametrize.html) for the set of CWL/DAGs we want to test. This will enable us to only have a single set of deploy, execute, status, and undeploy unit tests. The alternative is that we will end up with a set of deploy, execute, status, and undeploy unit tests for every CWL/DAG we would like to test. That would lead to a lot of duplicated code.

**Comment by nikki-t** [comment]
@drewm-jpl - This is a great idea. I am thinking that I can parameterize the four unit tests that I created to except different CWL/DAGs and point to where applicable the different execution request and process description JSON files alongside the expected process ID.

**Comment by drewm-swe** [comment]
Do you think you could parameterize the existing functions, so that we can exercise all of them with a set of CWLs/DAGs?

- `test_post_deploy_process`
- `test_delete_undeploy_process`
- `test_post_execute_process`
- `test_delete_dismiss_execution`
- `test_get_process_description`
- `test_get_process_list`
- `test_get_status`
- `test_get_results`


The parameterization could look something like this:
```python
# Parametrize for different process descriptions
@pytest.mark.parametrize("process_filename", [
    "test_data/process_descriptions/EchoProcess.json",
    "test_data/process_descriptions/AnotherProcess.json"
])
@pytest.fixture(scope="module")
def deploy_process(test_directory, client, process_filename):
```

Or even more generically like this to avoid hardcoding filenames:
```python
# Use glob to get all files in the process descriptions directory
process_files = glob.glob("test_data/process_descriptions/*.json")

@pytest.mark.parametrize("process_filename", process_files)
```

**Comment by nikki-t** [comment]
@drewm-jpl and @LucaCinquini - I really liked Drew's idea of using glob to discover all of the files in either the `process_descriptions` and `execution_requests` directories and then parametrize the unit tests using those files. I did need to implement a little bit of structure for this to work:

- JSON files must be named after the process ID which is located in the process description JSON files.
- Execution requests and process description JSON files must be named the same but organized into their respective directories: `execution_requests` and `process_descriptions`.
- To add a new CWL DAG you will need to create a process description file with the same name as the `id` property and then create an execution request file to describe the expected inputs and outputs with the same name as the process file then the unit tests will automatically discover and test that new CWL DAG.

I also feel like we may want to move the four unit tests that I created into more of an integration test set up since they rely on each other to a certain extent and follow the expected order of CWL DAG deployment, execution, and un-deployment but I don't think that is necessary for now.

Let me know if you have any feedback and/or if this is ready to be merged.

**Review by LucaCinquini — APPROVED** [review]
Hi Nikki, the changes look great, great job.
Only suggestion: could you please add a "workflow_dispatch:" trigger to the Github Action that executes the unity tests, so we can run them manually without a PR?

**Review by drewm-swe — COMMENTED** [review]
@nikki-t This looks great, nice work.

I have one more question, can we remove the existing `test_post_deploy_process`, `test_delete_undeploy_process`, `test_post_execute_process` functions now? It seems like there is overlap between what those functions test and what is tested by your new functions `test_post_deploy_process_dag`, `test_post_execute_process_dag`, `test_delete_undeploy_dag`. Perhaps we can consolidate them?

**Comment by nikki-t** [comment]
@LucaCinquini - I believe that I added the `workflow_dispatch` trigger and it should take effect when this is merged into main. At least I think that is how it works but let me know if I need to do anything else.

@drewm-jpl - Great suggestion, I felt like things were getting redundant so I removed the three tests you recommended.

**Review by drewm-swe — APPROVED** [review]
Looks good, nice work

**Comment by LucaCinquini** [comment]
@nikki-t please go ahead and merge, great progress.

**Pull request merged**
